'use strict';
const $=id=>document.getElementById(id),M=TrigoMath,PI=Math.PI;
const names={sin:'sen',cos:'cos',tan:'tan'};
let unit='rad',mode='explore',ast=M.parse('2sen(x)'),other=null,params={f:'sin',A:2,B:1,h:0,D:0},zoom=1,playing=false,phase=.5,lastTime=0,hoverX=null,score=0,solved=false,challengeIndex=0;
const identities=[['sen(x)^2+cos(x)^2','1','Para todo x: la suma de los cuadrados del seno y del coseno vale 1.'],['tan(x)','sen(x)/cos(x)','Se cumple donde cos(x) ≠ 0. Ambos lados quedan indefinidos cuando cos(x) = 0.'],['sen(2x)','2sen(x)cos(x)','El seno de un ángulo doble se expresa como un producto.'],['cos(2x)','cos(x)^2-sen(x)^2','El coseno de un ángulo doble se expresa como una diferencia de cuadrados.']];
const challenges=[{f:'sin',A:3,B:2,h:0,D:0},{f:'cos',A:2,B:1,h:PI/2,D:1},{f:'sin',A:1,B:.5,h:-PI/2,D:-1},{f:'tan',A:1,B:2,h:PI/4,D:0},{f:'cos',A:4,B:2,h:PI,D:-2}];
const round=v=>Math.abs(v)<1e-8?'0':Number(v.toFixed(3)).toString();
function angle(v){if(v===null||!Number.isFinite(v))return '—';if(unit==='deg')return round(v)+'°';for(let d=1;d<=16;d++){const n=Math.round(v/PI*d);if(Math.abs(v-n*PI/d)<1e-6){if(!n)return '0';return (n<0?'−':'')+(Math.abs(n)===1?'':Math.abs(n))+'π'+(d===1?'':'/'+d);}}return round(v);}
function escapeHTML(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function numeric(v){return v;}
function writeFormula(){const h=numeric(params.h),inner=h===0?'x':`(x${h<0?'+':'-'}${Math.abs(h)})`;return `${params.A}*${names[params.f]}(${params.B===0?(params.C??0):params.B+'*'+inner})${params.D===0?'':(params.D<0?'-':'+')+Math.abs(params.D)}`;}
function makeSliders(){
 $('sliders').innerHTML='';
 for(const [key,label,min,max,step,help] of [['A','A · escala vertical',-4,4,.25,'En seno y coseno, amplitud = |A|.'],['B','B · frecuencia',-4,4,.25,'Mayor |B| → período más corto. B = 0 da una constante.'],['h','h · desfasaje',unit==='rad'?-2*PI:-360,unit==='rad'?2*PI:360,unit==='rad'?PI/12:15,'h > 0: derecha. h < 0: izquierda.'],['D','D · traslado vertical',-4,4,.25,'Mueve la línea media hacia arriba o abajo.']]){
 const div=document.createElement('div');div.className='slider';div.innerHTML=`<label for="slider-${key}">${label}<output id="out-${key}"></output></label><input id="slider-${key}" type="range" min="${Math.min(min,params[key])}" max="${Math.max(max,params[key])}" step="${step}" value="${params[key]}"><small>${help}</small>`;$('sliders').append(div);
 $('slider-'+key).addEventListener('input',e=>{params[key]=Number(e.target.value);updateFromControls();});
 }
 $('kind').value=params.f;updateOutputs();
}
function updateOutputs(){for(const key of ['A','B','h','D'])$('out-'+key).textContent=key==='h'?angle(params[key]):round(params[key]);}
function updateFromControls(){ast=M.parse(writeFormula());$('formula').value=writeFormula();$('error').textContent='';updateOutputs();refresh();}
function parseFormula(){try{const next=M.parse($('formula').value);const props=M.properties(next,unit);ast=next;if(props){params={f:props.f,A:props.A,B:props.B,C:props.C,h:props.shift??0,D:props.D};makeSliders();}$('error').textContent='';phase=0;refresh();}catch(e){$('error').textContent=e.message;}}
$('formula-form').addEventListener('submit',e=>{e.preventDefault();parseFormula();});$('kind').onchange=()=>{params.f=$('kind').value;updateFromControls();};$('base').onchange=refresh;
$('reset').onclick=()=>{params={f:'sin',A:1,B:1,h:0,D:0};zoom=1;phase=0;makeSliders();updateFromControls();};
function setUnit(next){if(next===unit)return;const p=M.properties(ast,unit);const scale=next==='deg'?180/PI:PI/180;unit=next;if(p){params={f:p.f,A:p.A,B:p.B,C:p.C*scale,h:(p.shift??0)*scale,D:p.D};const formula=p.B===0?`${p.A}*${names[p.f]}(${numeric(p.C*scale)})${p.D<0?'-':'+'}${Math.abs(p.D)}`:writeFormula();ast=M.parse(formula);$('formula').value=formula;}else {params.h*=scale;$('error').textContent='Esta expresión libre conserva lo escrito al cambiar de unidad. Revisá sus constantes angulares.';}makeSliders();$('rad').classList.toggle('selected',unit==='rad');$('deg').classList.toggle('selected',unit==='deg');if(mode==='identity')compare();renderTarget();hoverX=null;refresh();}
$('rad').onclick=()=>setUnit('rad');$('deg').onclick=()=>setUnit('deg');
for(const button of document.querySelectorAll('nav button'))button.onclick=()=>{mode=button.dataset.mode;document.querySelector('.layout').hidden=mode==='formulas';$('compare-mode').hidden=mode!=='formulas';if(mode==='formulas'){playing=false;$('play').textContent='▶ Animar';}for(const b of document.querySelectorAll('nav button'))b.classList.toggle('active',b===button);for(const id of ['explore','identity','challenge'])$(id).hidden=(id==='explore'?mode==='identity':id!==mode);hoverX=null;if(mode==='identity')loadIdentity();refresh();};
function loadIdentity(){const [a,b,text]=identities[Number($('identity-choice').value)];$('left').value=a;$('right').value=b;$('identity-text').textContent=text;compare();}
$('identity-choice').onchange=loadIdentity;
let identityLeft=null;
function compare(){try{const a=M.parse($('left').value),b=M.parse($('right').value);identityLeft=a;other=b;$('identity-error').textContent='';let max=0,count=0,undefinedCount=0,mismatchDomain=0;const half=unit==='rad'?2*PI:360;for(let i=0;i<=720;i++){const x=-half+2*half*i/720,u=M.evaluate(a,x,unit),v=M.evaluate(b,x,unit);if(Number.isFinite(u)&&Number.isFinite(v)){max=Math.max(max,Math.abs(u-v));count++;}else{undefinedCount++;if(Number.isFinite(u)!==Number.isFinite(v))mismatchDomain++;}}$('identity-result').textContent=`${count} puntos comparados. ${max<1e-7&&count?'Los valores coinciden en los puntos evaluados.':count?'Los valores difieren en al menos un punto.':'No hay valores finitos para comparar.'}${undefinedCount?' '+undefinedCount+' puntos con algún lado indefinido.':''}${mismatchDomain?' Atención: en '+mismatchDomain+' puntos solo uno de los lados está definido.':''} El muestreo no demuestra una identidad.`;refresh();}catch(e){$('identity-error').textContent=e.message;}}
$('compare').onclick=compare;
function activeAst(){return mode==='identity'?identityLeft:ast;}
function secondAst(){if(mode==='identity')return other;const p=M.properties(ast,unit);return $('base').checked&&p?M.parse(names[p.f]+'(x)'):null;}
function metric(title,value,note){return `<div class="metric"><small>${title}</small><strong>${escapeHTML(value)}</strong><span>${escapeHTML(note)}</span></div>`;}
function refresh(){
 $('motion-body').closest('.motion-card').hidden=mode==='identity';
 const n=activeAst();if(!n)return;const p=M.properties(n,unit);
 $('graph-title').textContent=mode==='identity'?$('left').value+' = '+$('right').value:$('formula').value;
 $('legend-main').textContent=mode==='identity'?'Lado izquierdo':'Tu función';$('legend-second-text').textContent=mode==='identity'?'Lado derecho':'Función base';$('legend-secondary').hidden=!secondAst();
 if(mode==='identity'){$('metrics').innerHTML='';$('explanation').innerHTML='<h3>Mirar también el dominio</h3><p>Las curvas que coinciden sugieren equivalencia. Revisá dónde está definido cada lado y justificá la identidad algebraicamente.</p>';}
 else if(!p){$('metrics').innerHTML='';$('explanation').innerHTML='<h3>Una expresión para explorar</h3><p>La gráfica y la tabla están disponibles. Los indicadores automáticos se muestran para A·sen(Bx+C)+D, A·cos(Bx+C)+D o A·tan(Bx+C)+D. Si movés un control, se reemplaza esta expresión por la forma de los controles.</p>';}
 else if(p.constant){$('metrics').innerHTML=metric('Amplitud','—','Función constante')+metric('Período fundamental','—','No tiene período mínimo positivo')+metric('Desfasaje','—','No identifica una onda')+metric('Traslado D',round(p.D),'Parámetro de la fórmula');$('explanation').innerHTML='<h3>¿Dónde quedó la onda?</h3><p>Con A = 0 o B = 0, la expresión es constante en los puntos donde está definida. No tiene un período fundamental. Probá valores distintos de cero para recuperar la onda.</p>';}
 else{
 $('metrics').innerHTML=metric('Amplitud',p.f==='tan'?'No tiene':round(p.amplitude),p.f==='tan'?'|A| escala verticalmente':'Distancia a la línea media')+metric('Período',angle(p.period),unit==='deg'?(p.f==='tan'?'180° / |B|':'360° / |B|'):(p.f==='tan'?'π / |B| en radianes':'2π / |B| en radianes'))+metric('Desfasaje h',angle(p.shift),Math.abs(p.shift)<1e-8?'Sin desplazamiento':p.shift>0?'Hacia la derecha':'Hacia la izquierda')+metric(p.f==='tan'?'Traslado vertical':'Línea media',round(p.D),'y = '+round(p.D));
 const turn=unit==='deg'?180:PI,exclude=p.f==='tan'?`Dominio: todos los valores salvo x = ${angle(p.shift)} + (${angle(turn/2)} + k·${angle(turn)}) / ${round(p.B)}, con k entero. Imagen: todos los reales. Las líneas discontinuas son asíntotas verticales.`:`Dominio: todos los reales. Imagen: [${round(p.D-p.amplitude)}, ${round(p.D+p.amplitude)}].`;
 $('explanation').innerHTML='<h3>Leé lo que cambió</h3><p>'+escapeHTML(exclude)+'</p><p>'+escapeHTML(p.f==='tan'?'La tangente no tiene máximos ni mínimos y no tiene amplitud. El factor A modifica la escala de cada rama.':`La altura desde la línea media es ${round(p.amplitude)}. La curva se repite cada ${angle(p.period)}.`)+'</p><p>'+escapeHTML(p.A<0?'A negativo refleja verticalmente la curva respecto de y = D. ':'')+escapeHTML('En A·f(Bx+C)+D, el desfasaje es h = −C/B. Los desplazamientos que difieren en un período producen la misma gráfica.')+'</p>';
 }
 buildTable();draw();
}
function bounds(){const p=M.properties(activeAst(),unit);const half=(unit==='deg'?360:2*PI)*zoom;let y=3;const constantValue=M.evaluate(activeAst(),0,unit);if((p?.constant||M.linear(activeAst())?.[0]===0)&&Number.isFinite(constantValue))y=Math.max(y,Math.abs(constantValue)+1);if(p&&!p.constant&&p.f!=='tan')y=Math.max(3,Math.abs(p.D)+p.amplitude+1);if(p&&p.f==='tan')y=Math.max(4,Math.abs(p.D)+Math.abs(p.A)*2);return {xmin:-half,xmax:half,ymin:-y,ymax:y};}
const canvas=$('graph'),ctx=canvas.getContext('2d');let width=800,height=380;
function draw(){
 if(!activeAst())return;const motionBounds=bounds();TrigoMotion.render({p:M.properties(ast,unit),x:hoverX===null?motionBounds.xmin+(motionBounds.xmax-motionBounds.xmin)*phase:hoverX,unit,mode,phase,playing,bounds:motionBounds,angle});const rect=canvas.getBoundingClientRect(),dpr=window.devicePixelRatio||1;width=rect.width;height=rect.height;if(!width)return;if(canvas.width!==Math.round(width*dpr)||canvas.height!==Math.round(height*dpr)){canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,width,height);ctx.fillStyle='#fff';ctx.fillRect(0,0,width,height);
 const b=bounds(),pad={l:44,r:14,t:20,b:32},W=width-pad.l-pad.r,H=height-pad.t-pad.b,px=x=>pad.l+(x-b.xmin)/(b.xmax-b.xmin)*W,py=y=>pad.t+(b.ymax-y)/(b.ymax-b.ymin)*H;
 ctx.font='11px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.lineWidth=1;
 const step=(unit==='deg'?90:PI/2)*zoom;
 for(let i=-4;i<=4;i++){const x=i*step;ctx.strokeStyle='#edf0f7';ctx.beginPath();ctx.moveTo(px(x),pad.t);ctx.lineTo(px(x),height-pad.b);ctx.stroke();ctx.fillStyle='#858a9e';ctx.fillText(angle(x),px(x),height-13);}
 const ystep=Math.max(1,Math.ceil(b.ymax/4));for(let y=Math.ceil(b.ymin/ystep)*ystep;y<=b.ymax;y+=ystep){ctx.strokeStyle='#edf0f7';ctx.beginPath();ctx.moveTo(pad.l,py(y));ctx.lineTo(width-pad.r,py(y));ctx.stroke();ctx.fillStyle='#858a9e';ctx.textAlign='right';ctx.fillText(round(y),pad.l-9,py(y));}ctx.textAlign='center';
 ctx.strokeStyle='#c3c7d7';ctx.beginPath();ctx.moveTo(pad.l,py(0));ctx.lineTo(width-pad.r,py(0));ctx.moveTo(px(0),pad.t);ctx.lineTo(px(0),height-pad.b);ctx.stroke();ctx.fillStyle='#6f7488';ctx.fillText('x',width-8,py(0)-12);ctx.fillText('y',px(0)+12,12);
 const p=M.properties(activeAst(),unit);ctx.save();ctx.beginPath();ctx.rect(pad.l,pad.t,W,H);ctx.clip();
 if(mode!=='identity'&&p&&!p.constant){
 ctx.setLineDash([5,5]);ctx.strokeStyle='#c6b6f7';ctx.beginPath();ctx.moveTo(pad.l,py(p.D));ctx.lineTo(width-pad.r,py(p.D));ctx.stroke();
 if(p.f==='tan'){const turn=unit==='deg'?180:PI;const start=Math.floor((p.B*b.xmin+p.C-turn/2)/turn)-2,end=Math.ceil((p.B*b.xmax+p.C-turn/2)/turn)+2;for(let k=Math.min(start,end);k<=Math.max(start,end)&&k<Math.min(start,end)+300;k++){const x=(turn/2+k*turn-p.C)/p.B;if(x>=b.xmin&&x<=b.xmax){ctx.strokeStyle='#e5b280';ctx.beginPath();ctx.moveTo(px(x),pad.t);ctx.lineTo(px(x),height-pad.b);ctx.stroke();}}}
 else {ctx.strokeStyle='#b7a4ed';const start=Math.max(b.xmin,p.shift),end=start+p.period;if(end<=b.xmax){ctx.beginPath();ctx.moveTo(px(start),pad.t+10);ctx.lineTo(px(end),pad.t+10);ctx.moveTo(px(start),pad.t+5);ctx.lineTo(px(start),pad.t+15);ctx.moveTo(px(end),pad.t+5);ctx.lineTo(px(end),pad.t+15);ctx.stroke();ctx.fillStyle='#6c46df';ctx.fillText('un período',(px(start)+px(end))/2,pad.t+26);}}
 ctx.setLineDash([]);
 }
 function curve(n,color,dashed){if(!n)return;const curveProps=M.properties(n,unit),turn=unit==='deg'?180:PI;const branch=x=>curveProps&&curveProps.f==='tan'&&curveProps.B!==0?Math.floor((curveProps.B*x+curveProps.C-turn/2)/turn):0;ctx.strokeStyle=color;ctx.lineWidth=dashed?3:2.5;ctx.setLineDash(dashed?[7,5]:[]);ctx.beginPath();let prev=null;const sampleCount=Math.min(16000,Math.max(Math.ceil(W*3),p?Math.ceil(Math.abs(p.B)*zoom*160):0));for(let i=0;i<=sampleCount;i++){const x=b.xmin+(b.xmax-b.xmin)*i/sampleCount,y=M.evaluate(n,x,unit);if(!Number.isFinite(y)||y<b.ymin-1||y>b.ymax+1){prev=null;continue;}const X=px(x),Y=py(y);if(prev&&prev.branch===branch(x)&&Math.abs(Y-prev.Y)<H*.55)ctx.lineTo(X,Y);else ctx.moveTo(X,Y);prev={X,Y,branch:branch(x)};}ctx.stroke();ctx.setLineDash([]);}
 curve(activeAst(),'#6c46df',false);curve(secondAst(),'#078d89',true);
 const x=hoverX===null?b.xmin+(b.xmax-b.xmin)*phase:hoverX,y=M.evaluate(activeAst(),x,unit);if(Number.isFinite(y)&&y>=b.ymin&&y<=b.ymax){ctx.strokeStyle='#f59d3870';ctx.setLineDash([3,4]);ctx.beginPath();ctx.moveTo(px(x),py(0));ctx.lineTo(px(x),py(y));ctx.stroke();ctx.setLineDash([]);ctx.beginPath();ctx.arc(px(x),py(y),6,0,2*PI);ctx.fillStyle='#f59d38';ctx.fill();ctx.strokeStyle='white';ctx.lineWidth=2;ctx.stroke();}ctx.restore();$('point').textContent=`x = ${angle(x)} · y = ${Number.isFinite(y)?round(y):'no definida'}${Number.isFinite(y)&&(y<b.ymin||y>b.ymax)?' (fuera de la ventana vertical)':''}`;
}
canvas.onpointermove=e=>{const rect=canvas.getBoundingClientRect(),b=bounds();hoverX=Math.max(b.xmin,Math.min(b.xmax,b.xmin+(e.clientX-rect.left-44)/(rect.width-58)*(b.xmax-b.xmin)));draw();};canvas.onpointerleave=()=>{hoverX=null;draw();};new ResizeObserver(draw).observe(canvas);
function tick(t){if(playing){const dt=lastTime?Math.min((t-lastTime)/1000,.1):0;phase=(phase+dt*Number($('speed').value)/12)%1;hoverX=null;draw();}lastTime=t;requestAnimationFrame(tick);}requestAnimationFrame(tick);
$('play').onclick=()=>{playing=!playing;$('play').textContent=playing?'Ⅱ Pausar':'▶ Animar';draw();};$('zoom-in').onclick=()=>{zoom=Math.max(.125,zoom/2);refresh();};$('zoom-out').onclick=()=>{zoom=Math.min(8,zoom*2);refresh();};
let rows=[];
function buildTable(){const b=bounds();rows=[];const n=activeAst(),s=secondAst();for(let i=0;i<=8;i++){const x=b.xmin+(b.xmax-b.xmin)*i/8;rows.push([x,M.evaluate(n,x,unit),s?M.evaluate(s,x,unit):null]);}$('table').innerHTML=`<table><thead><tr><th>x (${unit==='rad'?'rad':'°'})</th><th>${mode==='identity'?'Izquierdo':'f(x)'}</th>${s?'<th>'+ (mode==='identity'?'Derecho':'Base')+'</th>':''}</tr></thead><tbody>${rows.map(r=>'<tr><td>'+angle(r[0])+'</td><td>'+(Number.isFinite(r[1])?round(r[1]):'No definida')+'</td>'+(s?'<td>'+(Number.isFinite(r[2])?round(r[2]):'No definida')+'</td>':'')+'</tr>').join('')}</tbody></table>`;}
function download(url,name){const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();}
$('png').onclick=()=>{draw();const exportCanvas=document.createElement('canvas');exportCanvas.width=canvas.width;exportCanvas.height=canvas.height+110*(devicePixelRatio||1);const e=exportCanvas.getContext('2d');e.fillStyle='white';e.fillRect(0,0,exportCanvas.width,exportCanvas.height);e.drawImage(canvas,0,70*(devicePixelRatio||1));e.scale(devicePixelRatio||1,devicePixelRatio||1);e.fillStyle='#202641';e.font='bold 16px system-ui';e.fillText('TrigoLab · '+$('graph-title').textContent,20,30);e.font='12px system-ui';e.fillText('Eje x en '+(unit==='rad'?'radianes':'grados')+' · Violeta: '+$('legend-main').textContent+' · Verde: '+$('legend-second-text').textContent,20,53);download(exportCanvas.toDataURL('image/png'),'trigolab-grafica.png');};
$('csv').onclick=()=>{const s=secondAst();const data='\uFEFFx_'+unit+';funcion'+(s?';comparacion':'')+'\r\n'+rows.map(r=>[r[0],Number.isFinite(r[1])?r[1]:'No definida',...(s?[Number.isFinite(r[2])?r[2]:'No definida']:[])].join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([data],{type:'text/csv;charset=utf-8'}));download(url,'trigolab-tabla.csv');setTimeout(()=>URL.revokeObjectURL(url),1000);};
function currentTarget(){const t=challenges[challengeIndex%challenges.length];return {...t,h:t.h*(unit==='deg'?180/PI:1)};}
function renderTarget(){const t=currentTarget(),period=(unit==='deg'?(t.f==='tan'?180:360):(t.f==='tan'?PI:2*PI))/Math.abs(t.B);$('target').textContent=`Función: ${t.f==='sin'?'seno':t.f==='cos'?'coseno':'tangente'}. ${t.f==='tan'?'Escala vertical A = '+t.A:'Amplitud = '+t.A}. Período = ${angle(period)}. Desfasaje = ${angle(t.h)}. Traslado vertical D = ${t.D}.`;$('score').textContent='Desafíos resueltos: '+score;}
$('check-challenge').onclick=()=>{const p=M.properties(ast,unit),t=currentTarget(),period=(unit==='deg'?(t.f==='tan'?180:360):(t.f==='tan'?PI:2*PI))/Math.abs(t.B);const sameShift=p&&p.shift!==null&&Math.abs((p.shift-t.h)/period-Math.round((p.shift-t.h)/period))<1e-6;const ok=p&&!p.constant&&p.f===t.f&&Math.abs(p.period-period)<1e-6&&Math.abs(p.D-t.D)<1e-6&&Math.abs((t.f==='tan'?p.A:p.amplitude)-t.A)<1e-6&&sameShift;$('feedback').textContent=ok?'¡Lo lograste! Ahora explicá qué controla cada parámetro.':'Todavía falta. Revisá la altura, la repetición y los desplazamientos.';if(ok&&!solved){score++;solved=true;renderTarget();}};
$('next-challenge').onclick=()=>{challengeIndex++;solved=false;$('feedback').textContent='';renderTarget();};$('help').onclick=()=>$('guide').showModal();$('close-guide').onclick=()=>$('guide').close();
$('jump-motion').onclick=()=>{document.querySelector('nav button[data-mode=explore]').click();if($('motion-body').hidden)$('motion-toggle').click();$('motion-title').scrollIntoView({block:'start'});};
$('motion-edit').onclick=()=>$('explore').scrollIntoView({block:'start'});
TrigoMotion.init({
 play:()=>{$('play').click();},
 seek:value=>{playing=false;$('play').textContent='▶ Animar';phase=value;hoverX=null;draw();},
 unit:setUnit,
 speed:value=>{$('speed').value=value;},
 preset:(lesson,index)=>{playing=false;$('play').textContent='▶ Animar';params={f:'sin',A:lesson.A,B:lesson.B,h:lesson.h,D:lesson.D};zoom=1;phase=index===3?.625:.5;hoverX=null;makeSliders();updateFromControls();}
});
$('speed').addEventListener('input',()=>{$('motion-speed').value=$('speed').value;});
makeSliders();renderTarget();refresh();
